#include<stdio.h>
#include<conio.h>

void main ()  {
int gasto[5] ;
int dia ;
int maxgasto ;
int flag =0 ;
clrscr () ;
		 for (int i=0; i<5;i++) {
		 printf("ingrese importe de gasto del dia\n") ;
		 scanf("%d",&gasto[i]) ;


				      }//cierre del for

		   for (i=0 ; i<5;i++) {
		   if (flag==0 || gasto[i]>maxgasto )
			 maxgasto = gasto[i]
			 dia = i



			   }//cierre del for


	   getch () ;


 }//cierre del main